name: Linear
description: "Full time Emberjs front-end developer"
meta_description: "Full time Emberjs front-end developer"

markdown: redcarpet
highlighter: rogue
logo: false
paginate: 15
baseurl: /
domain_name: 'http://linear.co.za'
google_analytics: 'UA-59406852-1'

# Details for the RSS feed generator
url:            'www.linear.co.za'
author:         'Linear'

