name: Linear
description: "Hello. I do Emberjs."
meta_description: "Hello. I do Emberjs."

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.linear.co.za'
google_analytics: 'UA-59406852-1'
gems: [jekyll-feed, jekyll-paginate, jekyll-mentions]

future: true

# Details for the RSS feed generator
url:            'www.linear.co.za'
author:         'Linear'

