name: Linear
description: though not finite
meta_description: "On front end development"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://linear.co.za'
google_analytics: 'UA-59406852-1'

# Details for the RSS feed generator
url:            'www.linear.co.za'
author:         'Linearza'

